#!/bin/bash
echo "Testing BabylonFish 3.0..."
echo "App bundle: dist/BabylonFish3.app"
echo ""
echo "To test:"
echo "1. Open dist/BabylonFish3.app"
echo "2. Grant Accessibility and Input Monitoring permissions"
echo "3. Test typing in TextEdit or any text editor:"
echo "   - Type 'ghbdtn' (English layout) → should switch to Russian 'привет'"
echo "   - Type 'привет' (Russian layout) → should switch to English 'ghbdtn'"
echo "   - Test typo correction: 'havv' → 'have'"
echo "   - Test auto-completion"
echo ""
echo "Check debug logs: tail -f ~/babylonfish_debug.log"
